export const ADD_CATOGRY_REQUEST = "ADD_CATOGRY_REQUEST";
export const ADD_CATOGRY_SUCCESS = "ADD_CATOGRY_SUCCESS";
export const ADD_CATOGRY_FAILURE = "ADD_CATOGRY_FAILURE";
export const ADD_CATOGRY_RESET = "ADD_CATOGRY_RESET";